//==============================================================================
// clock_gen.v
//------------------------------------------------------------------------------
// Generates all clocks the pipeline needs from the Basys 3 100 MHz master clock.
//
//   clk_100m  -> input (from onboard oscillator, pin W5)
//   clk_25m   -> VGA pixel clock (100 MHz divided by 4)
//   xclk_25m  -> OV7670 XCLK input (100 MHz divided by 4, same as VGA clock)
//
// Notes
// -----
// * The OV7670 datasheet allows XCLK between 10 and 48 MHz; 25 MHz is inside
//   that range and is the simplest to generate from the Basys 3 clock.
// * VGA 640x480@60Hz spec is 25.175 MHz but 25.000 MHz is accepted by every
//   modern monitor.
// * For tight tolerance (simulation, HDMI, etc.) replace this divider with an
//   MMCM instance generated by the Clocking Wizard IP. A commented MMCM
//   template is provided at the bottom of the file.
//==============================================================================
`timescale 1ns / 1ps

module clock_gen (
    input  wire clk_100m,
    input  wire rst_n,
    output wire clk_25m,
    output wire xclk_25m
);

    // /4 counter. Toggle every 2 cycles -> 25 MHz with 50% duty.
    reg [1:0] div;
    always @(posedge clk_100m) begin
        if (!rst_n) div <= 2'b00;
        else        div <= div + 2'b01;
    end

    // div[1] toggles every 2 input clocks -> 25 MHz square wave
    assign clk_25m  = div[1];
    assign xclk_25m = div[1];

    // --------------------------------------------------------------------------
    // Alternative: use an MMCM for glitch-free clocks. Instantiate the Clocking
    // Wizard IP in Vivado to generate clk_25m at 25.000 MHz from the 100 MHz
    // input, then replace the divider above with its output. Template:
    //
    //   clk_wiz_0 u_mmcm (
    //       .clk_in1 (clk_100m),
    //       .reset   (~rst_n),
    //       .locked  (locked),
    //       .clk_out1(clk_25m)  // 25 MHz
    //   );
    //   assign xclk_25m = clk_25m;
    // --------------------------------------------------------------------------

endmodule
